# Generated by Django 4.1.3 on 2022-11-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_eventoproyecto_precio_mlc_acumulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoequipamiento',
            name='precio_mlc_acumulado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
