# Generated by Django 4.1.3 on 2022-11-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llamado', '0004_auto_20221102_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamadoproyecto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
