# Generated by Django 3.1.2 on 2022-11-02 21:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('documento', models.FileField(upload_to='documentos/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'db_table': 'epp_documento',
                'ordering': ['id'],
                'permissions': (('enable_documento', 'Can enable documento'), ('disable_documento', 'Can disable documento'), ('download_documento', 'Can download documento')),
            },
        ),
        migrations.CreateModel(
            name='EquipoProteccionPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('tipo_aprobacion', models.CharField(max_length=250)),
                ('fecha_vencimiento_certificado', models.DateField()),
                ('modelo', models.CharField(blank=True, max_length=250, null=True)),
                ('numero_referencia', models.CharField(blank=True, max_length=15, null=True)),
                ('clientes_usuarios', models.CharField(max_length=500)),
                ('muestras_equipo', models.BooleanField()),
                ('renovado', models.BooleanField(default=False)),
                ('equipo_ya_certificado', models.BooleanField(default=False)),
                ('fecha_renovacion', models.DateTimeField(blank=True, null=True)),
                ('primera_img', models.ImageField(blank=True, null=True, upload_to='primeras_img_epp/')),
                ('segunda_img', models.ImageField(blank=True, null=True, upload_to='segundas_img_epp/')),
                ('tercera_img', models.ImageField(blank=True, null=True, upload_to='terceras_img_epp/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'equipo proteccion personal',
                'verbose_name_plural': 'equipos de proteccion personal',
                'db_table': 'equipo_proteccion_personal',
                'ordering': ['id'],
                'permissions': (('enable_equipo_proteccion_personal', 'Can enable equipo proteccion personal'), ('disable_equipo_proteccion_personal', 'Can disable equipo proteccion personal'), ('renew_equipo_proteccion_personal', 'Can renew equipo proteccion personal'), ('delete_equipo_proteccion_personal_seleccionados', 'Can delete equipo proteccion personal seleccionados'), ('view_menu_equipo_proteccion_personal', 'Can view menu equipo proteccion personal'), ('view_listado_reportes', 'Can view view listado reportes'), ('view_reporte_equipo_proteccion_personal_registrado', 'Can view view_reporte equipo proteccion personal registrado'), ('view_reporte_equipo_proteccion_personal_aprobado', 'Can view view_reporte equipo proteccion personal aprobado'), ('view_reporte_equipo_proteccion_personal_vencido', 'Can view view_reporte equipo proteccion personal vencido'), ('view_menu_reporte_principal', 'Can view view menu reporte principal'), ('view_menu_reporte', 'Can view view menu reporte'), ('export_factura', 'Can export factura'), ('export_prefactura', 'Can export prefactura'), ('export_certificado_epp', 'Can export certificado epp')),
            },
        ),
        migrations.CreateModel(
            name='NumeroPrefactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_prefactura', models.CharField(max_length=15, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeroprefactura_entidad', to='nomencladores.entidad')),
            ],
            options={
                'verbose_name': 'numero prefactura',
                'verbose_name_plural': 'numeros prefactura',
                'db_table': 'epp_numero_prefactura',
                'ordering': ['id'],
                'permissions': (('enable_numero_prefactura', 'Can enable numero prefactura'), ('disable_numero_prefactura', 'Can disable numero prefactura')),
            },
        ),
        migrations.CreateModel(
            name='HistorialEPPRenovado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renovado', models.BooleanField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo_proteccion_personal.equipoproteccionpersonal')),
            ],
            options={
                'db_table': 'epp_historial_epp_renovado',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('CUP', 'CUP'), ('MLC', 'MLC')], max_length=15)),
                ('cantidad_cup', models.IntegerField()),
                ('cantidad_mlc', models.IntegerField()),
                ('cantidad_equipos', models.IntegerField()),
                ('estado_pago', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_limite_pago', models.DateField()),
                ('elaborado_nombre', models.CharField(max_length=250)),
                ('elaborado_cargo', models.CharField(max_length=250)),
                ('revisado_nombre', models.CharField(max_length=250)),
                ('revisado_cargo', models.CharField(max_length=250)),
                ('entregado_registrado_nombre', models.CharField(max_length=250)),
                ('entregado_registrado_cargo', models.CharField(max_length=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('numero_prefactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo_proteccion_personal.numeroprefactura')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
                'db_table': 'epp_factura',
                'ordering': ['id'],
                'permissions': (('enable_factura', 'Can enable factura'), ('disable_factura', 'Can disable factura'), ('delete_factura_seleccionadas', 'Can delete factura seleccionadas'), ('pagar_factura', 'Can pagar factura'), ('view_reporte_factura', 'Can view reporte factura')),
            },
        ),
    ]
