version: '3'
services:
  
  db_postgres:
    #image: postgres:15.1-focal
    image: postgres:13.2-alpine
    #restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./backups:/backups
    env_file:
      - .env
  web_python:
    build: .
    #restart: always
    #command: python manage.py runserver 0.0.0.0:8000 
    #volumes:
    #  - ./volumen:/eppEstudio50-main
    ports:
      - "8000:8000"
    env_file:
      - .env  
    depends_on:
      - db_postgres