# Generated by Django 3.1.2 on 2022-11-02 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=250)),
                ('peso_maximo', models.CharField(max_length=250)),
                ('cantidad_persona', models.IntegerField()),
                ('persona_chofer', models.CharField(max_length=250)),
                ('anno_fabricacion', models.IntegerField()),
                ('precio_mlc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_cup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transporte_img', models.ImageField(blank=True, null=True, upload_to='transporte_img/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomencladores.marcatransporte')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomencladores.modelo')),
                ('sub_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomencladores.subcategoria')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomencladores.tipovehiculo')),
            ],
            options={
                'verbose_name': 'transporte',
                'verbose_name_plural': 'transportees',
                'db_table': 'transporte',
                'ordering': ['id'],
                'permissions': (('enable_transporte', 'Can enable transporte'), ('disable_transporte', 'Can disable transporte'), ('delete_transportes_seleccionados', 'Can delete transportes seleccionados'), ('view_menu_transporte', 'Can view menu transporte')),
            },
        ),
    ]
