# Generated by Django 3.1.2 on 2022-11-02 21:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('precio_cup', models.IntegerField()),
                ('precio_mlc', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'db_table': 'nomencladores_categoria',
                'ordering': ['id'],
                'permissions': (('enable_categoria', 'Can enable categoria'), ('disable_categoria', 'Can disable categoria')),
            },
        ),
        migrations.CreateModel(
            name='CategoriaLicenciaConduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoria lic conduccion',
                'verbose_name_plural': 'categorias lic conduccion',
                'db_table': 'nomencladores_categoria_lic_conduccion',
                'ordering': ['id'],
                'permissions': (('enable_categorialicenciaconduccion', 'Can enable categoria licencia conduccion'), ('disable_categorialicenciaconduccion', 'Can disable categoria licencia conduccion')),
            },
        ),
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoria_servicio',
                'verbose_name_plural': 'categorias de servicio',
                'db_table': 'nomencladores_categoria_servicio',
                'ordering': ['id'],
                'permissions': (('enable_categoriaservicio', 'Can enable categoriaservicio'), ('disable_categoriaservicio', 'Can disable categoriaservicio')),
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'idioma',
                'verbose_name_plural': 'idioma',
                'db_table': 'nomencladores_idioma',
                'ordering': ['id'],
                'permissions': (('enable_idioma', 'Can enable idioma'), ('disable_idioma', 'Can disable idioma')),
            },
        ),
        migrations.CreateModel(
            name='MarcaComercialRegistrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'marca_comercial_registrada',
                'verbose_name_plural': 'marcas comercial registrada',
                'db_table': 'nomencladores_marca_comercial_registrada',
                'ordering': ['id'],
                'permissions': (('enable_marca_comercial_registrada', 'Can enable marca comercial registrada'), ('disable_marca_comercial_registrada', 'Can disable marca comercial registrada')),
            },
        ),
        migrations.CreateModel(
            name='MarcaTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'marca transporte',
                'verbose_name_plural': 'marcas transporte',
                'db_table': 'nomencladores_marca_transporte',
                'ordering': ['id'],
                'permissions': (('enable_marcatransporte', 'Can enable marca transporte'), ('disable_marcatransporte', 'Can disable marca transporte')),
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'modelo',
                'verbose_name_plural': 'modelos',
                'db_table': 'nomencladores_modelo',
                'ordering': ['id'],
                'permissions': (('enable_modelo', 'Can enable modelo'), ('disable_modelo', 'Can disable modelo')),
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nacionalidad', models.CharField(blank=True, max_length=150, null=True)),
                ('siglas', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'pais',
                'verbose_name_plural': 'paises',
                'db_table': 'nomencladores_pais',
                'ordering': ['id'],
                'permissions': (('enable_pais', 'Can enable pais'), ('disable_pais', 'Can disable pais')),
            },
        ),
        migrations.CreateModel(
            name='ParteCuerpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'parte_cuerpo',
                'verbose_name_plural': 'partes del cuerpo',
                'db_table': 'nomencladores_parte_cuerpo',
                'ordering': ['id'],
                'permissions': (('enable_parte_cuerpo', 'Can enable parte cuerpo'), ('disable_parte_cuerpo', 'Can disable parte cuerpo')),
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'provincia',
                'verbose_name_plural': 'provincias',
                'db_table': 'nomencladores_provincia',
                'ordering': ['id'],
                'permissions': (('enable_provincia', 'Can enable provincia'), ('disable_provincia', 'Can disable provincia')),
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'sexo',
                'verbose_name_plural': 'sexos',
                'db_table': 'nomencladores_sexo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoArquitectura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo arquitectura',
                'verbose_name_plural': 'tipos de arquitectura',
                'db_table': 'nomencladores_tipo_arquitectura',
                'ordering': ['id'],
                'permissions': (('enable_tipoarquitectura', 'Can enable tipo arquitectura'), ('disable_tipoarquitectura', 'Can disable tipo arquitectura')),
            },
        ),
        migrations.CreateModel(
            name='TipoEntidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('tipo', models.CharField(choices=[('Nacional', 'Nacional'), ('Extranjera', 'Extranjera')], max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo_entidad',
                'verbose_name_plural': 'tipos de entidad',
                'db_table': 'nomencladores_tipo_entidad',
                'ordering': ['id'],
                'permissions': (('enable_tipo_entidad', 'Can enable tipo entidad'), ('disable_tipo_entidad', 'Can disable tipo entidad')),
            },
        ),
        migrations.CreateModel(
            name='TipoLugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo_lugar',
                'verbose_name_plural': 'tipos de lugar',
                'db_table': 'nomencladores_tipo_lugar',
                'ordering': ['id'],
                'permissions': (('enable_tipolugar', 'Can enable tipo lugar'), ('disable_tipolugar', 'Can disable tipo lugar')),
            },
        ),
        migrations.CreateModel(
            name='TipoSuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo_suelo',
                'verbose_name_plural': 'tipos de suelo',
                'db_table': 'nomencladores_tipo_suelo',
                'ordering': ['id'],
                'permissions': (('enable_tipo_suelo', 'Can enable tipo suelo'), ('disable_tipo_suelo', 'Can disable tipo suelo')),
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo_vehiculo',
                'verbose_name_plural': 'tipos de vehiculo',
                'db_table': 'nomencladores_tipo_vehiculo',
                'ordering': ['id'],
                'permissions': (('enable_tipovehiculo', 'Can enable tipo vehiculo'), ('disable_tipovehiculo', 'Can disable tipo vehiculo')),
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomencladores.categoriaservicio')),
            ],
            options={
                'verbose_name': 'sub_categoria',
                'verbose_name_plural': ' sub categorias',
                'db_table': 'nomencladores_sub_categoria',
                'ordering': ['id'],
                'permissions': (('enable_subcategoria', 'Can enable subcategoria'), ('disable_subcategoria', 'Can disable subcategoria')),
            },
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('siglas', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('hijode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nomencladores.organismo')),
            ],
            options={
                'verbose_name': 'organismo',
                'verbose_name_plural': 'organismos',
                'db_table': 'nomencladores_organismo',
                'ordering': ['id'],
                'permissions': (('enable_organismo', 'Can enable organismo'), ('disable_organismo', 'Can disable organismo')),
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('plan_turquino', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomencladores.provincia')),
            ],
            options={
                'verbose_name': 'municipio',
                'verbose_name_plural': 'municipios',
                'db_table': 'nomencladores_municipio',
                'ordering': ['id'],
                'permissions': (('enable_municipio', 'Can enable municipio'), ('disable_municipio', 'Can disable municipio')),
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_reeup', models.CharField(blank=True, max_length=15, null=True)),
                ('num_contrato', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=250)),
                ('direccion_web', models.CharField(blank=True, max_length=250, null=True)),
                ('correo', models.EmailField(max_length=100)),
                ('num_lic_comercial_camara_comercio', models.CharField(blank=True, max_length=15, null=True)),
                ('num_acta_protocolizacion', models.CharField(blank=True, max_length=15, null=True)),
                ('identificacion_fiscal', models.CharField(blank=True, max_length=15, null=True)),
                ('num_escritura_publica', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_representante', models.CharField(max_length=250)),
                ('cargo_representante', models.CharField(max_length=250)),
                ('entidad_importadora', models.BooleanField()),
                ('almacen', models.BooleanField()),
                ('observaciones', models.TextField()),
                ('fecha_registro', models.DateTimeField(default=datetime.datetime(2022, 11, 2, 17, 59, 25, 562729))),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomencladores.municipio')),
                ('organismo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomencladores.organismo')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomencladores.pais')),
                ('tipo_entidad_extranjera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidad_tipo_entidad_extranjera', to='nomencladores.tipoentidad')),
                ('tipo_entidad_nacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidad_tipo_entidad_nacional', to='nomencladores.tipoentidad')),
            ],
            options={
                'verbose_name': 'entidad',
                'verbose_name_plural': 'entidades',
                'db_table': 'nomencladores_entidad',
                'ordering': ['id'],
                'permissions': (('enable_entidad', 'Can enable entidad'), ('disable_entidad', 'Can disable entidad'), ('view_menu_nomencladores', 'Can view menu nomencladores'), ('view_reporte_entidad', 'Can view view reporte entidad'), ('export_certificado_entidad', 'Can export certificado entidad')),
            },
        ),
    ]
