# Generated by Django 3.1.2 on 2022-11-07 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0004_auto_20221106_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 12, 57, 46, 734306)),
        ),
    ]
