# Generated by Django 3.1.2 on 2022-11-02 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('precio_mlc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_cup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('equipamiento_img', models.ImageField(blank=True, null=True, upload_to='equipamiento_img/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomencladores.marcacomercialregistrada')),
                ('sub_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomencladores.subcategoria')),
            ],
            options={
                'verbose_name': 'equipamiento',
                'verbose_name_plural': 'equipamientos',
                'db_table': 'equipamiento',
                'ordering': ['id'],
                'permissions': (('enable_equipamiento', 'Can enable equipamiento'), ('disable_equipamiento', 'Can disable equipamiento'), ('delete_equipamientos_seleccionados', 'Can delete equipamientos seleccionados'), ('view_menu_equipamiento', 'Can view menu equipamiento')),
            },
        ),
    ]
