# Generated by Django 3.1.2 on 2022-11-02 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('direccion_domicilio', models.CharField(blank=True, max_length=250, null=True)),
                ('nombre_producto', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('precio_mlc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_cup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('abastecimiento_img', models.ImageField(blank=True, null=True, upload_to='abastecimiento_img/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('sub_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomencladores.subcategoria')),
            ],
            options={
                'verbose_name': 'abastecimiento',
                'verbose_name_plural': 'abastecimientos',
                'db_table': 'abastecimiento',
                'ordering': ['id'],
                'permissions': (('enable_abastecimiento', 'Can enable abastecimiento'), ('disable_abastecimiento', 'Can disable abastecimiento'), ('delete_abastecimientos_seleccionados', 'Can delete abastecimientos seleccionados'), ('view_menu_abastecimiento', 'Can view menu abastecimiento')),
            },
        ),
    ]
