# Generated by Django 3.1.2 on 2022-11-02 21:59

import actor.utiles.validaciones
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=11, validators=[actor.utiles.validaciones.validacion_ci])),
                ('num_pasaporte', models.CharField(blank=True, max_length=11, null=True)),
                ('otro_documento', models.CharField(blank=True, max_length=200, null=True)),
                ('primer_nombre', models.CharField(max_length=255)),
                ('segundo_nombre', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('primer_apellido', models.CharField(max_length=255)),
                ('segundo_apellido', models.CharField(max_length=255)),
                ('apodo', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sexo', models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('habilidades', models.TextField()),
                ('estatura', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=100)),
                ('color_piel', models.CharField(choices=[('Blanco', 'Blanco'), ('Negro', 'Negro'), ('Mestizo', 'Mestizo')], max_length=20)),
                ('color_ojos', models.CharField(choices=[('Negro', 'Negro'), ('Marron', 'Marrón'), ('Verde', 'Verde'), ('Azul', 'Azul')], max_length=20)),
                ('tipo_pelo', models.CharField(choices=[('Lacio', 'Lacio'), ('Ondulado', 'Ondulado'), ('Rizado', 'Rizado'), ('Crespo', 'Crespo')], max_length=20)),
                ('tendencia_racial', models.CharField(choices=[('Afro', 'Afro'), ('Blanca', 'Blanca'), ('Amarilla', 'Amarilla'), ('Roja', 'Roja')], max_length=30)),
                ('cadera', models.CharField(blank=True, max_length=100, null=True)),
                ('cintura', models.CharField(blank=True, max_length=100, null=True)),
                ('hombro', models.CharField(blank=True, max_length=100, null=True)),
                ('calzado', models.CharField(max_length=100)),
                ('precio_mlc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_cup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('primera_img', models.ImageField(blank=True, null=True, upload_to='primeras_img_actor/')),
                ('segunda_img', models.ImageField(blank=True, null=True, upload_to='segundas_img_actor/')),
                ('tercera_img', models.ImageField(blank=True, null=True, upload_to='terceras_img_actor/')),
                ('cuarta_img', models.ImageField(blank=True, null=True, upload_to='cuartas_img_actor/')),
                ('quinta_img', models.ImageField(blank=True, null=True, upload_to='quintas_img_actor/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria_lic_conduccion', models.ManyToManyField(related_name='categoria_lic_conduccion', to='nomencladores.CategoriaLicenciaConduccion')),
                ('idioma', models.ManyToManyField(related_name='idioma', to='nomencladores.Idioma')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomencladores.municipio')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomencladores.pais')),
                ('subcategoria_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomencladores.subcategoria')),
            ],
            options={
                'verbose_name': 'actor',
                'verbose_name_plural': 'actores',
                'db_table': 'actor',
                'ordering': ['id'],
                'permissions': (('enable_actor', 'Can enable actor'), ('disable_actor', 'Can disable actor'), ('delete_actores_seleccionados', 'Can delete actores seleccionados'), ('view_menu_actor', 'Can view menu actor')),
            },
        ),
    ]
