# Generated by Django 3.1.2 on 2022-11-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llamado', '0003_llamadoproyecto_fecha_fin_llamado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamadoproyecto',
            name='fecha_fin_llamado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
