# Generated by Django 4.1.3 on 2022-11-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llamado', '0005_alter_llamadoproyecto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamadoproyecto',
            name='precio_mlc_acumulado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
