#$docker run --name pgadmin -e "PGADMIN_DEFAULT_EMAIL=name@example.com" -e "PGADMIN_DEFAULT_PASSWORD=admin" -p 5050:80 -d dpage/pgadmin4 
---
version: '2.2'
services:
  pgadmin:
    container_name: pgadmin
    #build: .
    image: dpage/pgadmin4:6.16
    env_file:
      - .env
    ports:
      - 5050:80     
    networks:
      - eppestudio_default  
networks:     
  eppestudio_default:
    external: true
    

       
