# Generated by Django 3.1.2 on 2022-11-02 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0002_auto_20221102_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 18, 51, 17, 689031)),
        ),
    ]
