# Generated by Django 3.1.2 on 2022-11-07 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llamado', '0004_auto_20221102_1851'),
        ('abastecimiento', '0001_initial'),
        ('transporte', '0001_initial'),
        ('locacion', '0001_initial'),
        ('actor', '0001_initial'),
        ('equipamiento', '0001_initial'),
        ('especialista', '0001_initial'),
        ('nomencladores', '0004_auto_20221106_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoTransporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('fecha_inicio_evento', models.DateTimeField()),
                ('fecha_fin_evento', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('transporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transporte.transporte')),
            ],
            options={
                'verbose_name': 'evento de transporte',
                'verbose_name_plural': 'eventos de transporte',
                'db_table': 'evento_de_transporte',
                'ordering': ['id'],
                'permissions': (('enable_eventotransporte', 'Can enable evento transporte'), ('disable_eventotransporte', 'Can disable evento transporte'), ('export_eventostransporte', 'Can export eventos transporte')),
            },
        ),
        migrations.CreateModel(
            name='EventoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('fecha_inicio_evento', models.DateTimeField()),
                ('fecha_fin_evento', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('actor', models.ManyToManyField(blank=True, related_name='actor', to='actor.Actor')),
                ('equipamiento', models.ManyToManyField(blank=True, related_name='equipamiento', to='equipamiento.Equipamiento')),
                ('llamado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='llamado.llamadoproyecto')),
                ('subcategoria_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomencladores.subcategoria')),
            ],
            options={
                'verbose_name': 'evento proyecto',
                'verbose_name_plural': 'eventos proyecto',
                'db_table': 'evento_proyecto',
                'ordering': ['id'],
                'permissions': (('enable_eventoproyecto', 'Can enable eventoproyecto'), ('disable_eventoproyecto', 'Can disable eventoproyecto'), ('export_eventosproyecto', 'Can export eventosproyecto')),
            },
        ),
        migrations.CreateModel(
            name='EventoLocacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('fecha_inicio_evento', models.DateTimeField()),
                ('fecha_fin_evento', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('locacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locacion.locacion')),
            ],
            options={
                'verbose_name': 'evento de locacion',
                'verbose_name_plural': 'eventos de locacion',
                'db_table': 'evento_de_locacion',
                'ordering': ['id'],
                'permissions': (('enable_eventolocacion', 'Can enable evento locacion'), ('disable_eventolocacion', 'Can disable evento locacion'), ('export_eventoslocacion', 'Can export eventos locacion')),
            },
        ),
        migrations.CreateModel(
            name='EventoEspecialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('fecha_inicio_evento', models.DateTimeField()),
                ('fecha_fin_evento', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('especialista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='especialista.especialista')),
            ],
            options={
                'verbose_name': 'evento del especialista',
                'verbose_name_plural': 'eventos del especialista',
                'db_table': 'evento_del_especialista',
                'ordering': ['id'],
                'permissions': (('enable_eventoespecialista', 'Can enable eventoespecialista'), ('disable_eventoespecialista', 'Can disable eventoespecialista'), ('export_eventosespecialista', 'Can export eventosespecialista')),
            },
        ),
        migrations.CreateModel(
            name='EventoEquipamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha_inicio_evento', models.DateTimeField()),
                ('fecha_fin_evento', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('equipamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipamiento.equipamiento')),
            ],
            options={
                'verbose_name': 'evento del equipamiento',
                'verbose_name_plural': 'eventos del equipamiento',
                'db_table': 'evento_del_equipamiento',
                'ordering': ['id'],
                'permissions': (('enable_eventoequipamiento', 'Can enable eventoequipamiento'), ('disable_eventoequipamiento', 'Can disable eventoequipamiento'), ('export_eventosequipamiento', 'Can export eventosequipamiento')),
            },
        ),
        migrations.CreateModel(
            name='EventoActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('fecha_inicio_evento', models.DateTimeField()),
                ('fecha_fin_evento', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actor.actor')),
            ],
            options={
                'verbose_name': 'evento del actor',
                'verbose_name_plural': 'eventos del actor',
                'db_table': 'evento_del_actor',
                'ordering': ['id'],
                'permissions': (('enable_eventoactor', 'Can enable eventoactor'), ('disable_eventoactor', 'Can disable eventoactor'), ('export_eventosactor', 'Can export eventosactor')),
            },
        ),
        migrations.CreateModel(
            name='EventoAbastecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('fecha_inicio_evento', models.DateTimeField()),
                ('fecha_fin_evento', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('abastecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimiento.abastecimiento')),
            ],
            options={
                'verbose_name': 'evento de abastecimiento',
                'verbose_name_plural': 'eventos de abastecimiento',
                'db_table': 'evento_de_abastecimiento',
                'ordering': ['id'],
                'permissions': (('enable_eventoabastecimiento', 'Can enable evento abastecimiento'), ('disable_eventoabastecimiento', 'Can disable evento abastecimiento'), ('export_eventosabastecimiento', 'Can export eventos abastecimiento')),
            },
        ),
    ]
