# Generated by Django 4.1.3 on 2022-11-28 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llamado', '0006_llamadoproyecto_precio_mlc_acumulado'),
        ('evento', '0005_eventoequipamiento_precio_mlc_acumulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoactor',
            name='llamado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='llamado.llamadoproyecto'),
        ),
    ]
