# Generated by Django 3.1.2 on 2022-11-07 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0003_auto_20221102_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 20, 42, 39, 134037)),
        ),
    ]
