# Generated by Django 4.1.3 on 2022-11-15 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0008_alter_categoria_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='fecha_registro',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 13, 0, 24, 125774)),
        ),
    ]
