# Generated by Django 3.1.2 on 2022-11-07 01:42

from django.db import migrations, models
import django.db.models.deletion
import especialista.utiles.validaciones


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomencladores', '0004_auto_20221106_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=11, validators=[especialista.utiles.validaciones.validacion_ci])),
                ('num_pasaporte', models.CharField(blank=True, max_length=11, null=True)),
                ('otro_documento', models.CharField(blank=True, max_length=200, null=True)),
                ('primer_nombre', models.CharField(max_length=255)),
                ('segundo_nombre', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('primer_apellido', models.CharField(max_length=255)),
                ('segundo_apellido', models.CharField(max_length=255)),
                ('apodo', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('sexo', models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('habilidades', models.TextField()),
                ('precio_mlc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_cup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('especialista_img', models.ImageField(blank=True, null=True, upload_to='especialista_img/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('idioma', models.ManyToManyField(related_name='idioma_especialista', to='nomencladores.Idioma')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomencladores.municipio')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomencladores.pais')),
                ('subcategoria_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomencladores.subcategoria')),
            ],
            options={
                'verbose_name': 'especialista',
                'verbose_name_plural': 'especialistas',
                'db_table': 'especialista',
                'ordering': ['id'],
                'permissions': (('enable_especialista', 'Can enable especialista'), ('disable_especialista', 'Can disable especialista'), ('delete_especialistas_seleccionados', 'Can delete especialistas seleccionados'), ('view_menu_especialistas', 'Can view menu especialistas')),
            },
        ),
    ]
