# Generated by Django 3.1.2 on 2022-11-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LlamadoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('centro_emergencia', models.CharField(max_length=250)),
                ('tipo_pago', models.CharField(choices=[('Medio LLamado', 'medio_llamado'), ('Llamado Completo', 'llamado_completo')], default='medio_llamado', max_length=25)),
                ('direccion_centro_emergencia', models.CharField(max_length=250)),
                ('production_call', models.DateTimeField()),
                ('courtesy_meal', models.DateTimeField()),
                ('crew_call', models.DateTimeField()),
                ('artist_call', models.DateTimeField()),
                ('ready_to_shoot', models.DateTimeField()),
                ('first_meal', models.DateTimeField(blank=True, null=True)),
                ('second_meal', models.DateTimeField(blank=True, null=True)),
                ('third_meal', models.DateTimeField(blank=True, null=True)),
                ('estimated_camera_wrap', models.DateTimeField()),
                ('observaciones', models.CharField(max_length=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'llamado proyecto',
                'verbose_name_plural': 'llamados proyecto',
                'db_table': 'llamado_proyecto',
                'ordering': ['id'],
                'permissions': (('enable_llamadoproyecto', 'Can enable llamado proyecto'), ('disable_llamadoproyecto', 'Can disable llamado proyecto'), ('delete_llamadosproyecto_seleccionados', 'Can delete llamados proyecto seleccionados')),
            },
        ),
    ]
