# Generated by Django 3.1.2 on 2022-11-02 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_proyecto', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'proyecto_historial_estado_proyecto',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('cliente', models.CharField(max_length=250)),
                ('emergencia', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado_proyecto', models.CharField(default='Creado', max_length=100)),
                ('fecha_estado_proyecto', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nomencladores.categoria')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'db_table': 'proyecto',
                'ordering': ['id'],
                'permissions': (('enable_proyecto', 'Can enable proyecto'), ('disable_proyecto', 'Can disable proyecto'), ('delete_proyecto_seleccionados', 'Can delete proyecto seleccionados'), ('view_menu_proyecto', 'Can view_menu_proyecto'), ('update_estado_proyecto', 'Can update estado proyecto')),
            },
        ),
    ]
