# Generated by Django 4.1.3 on 2022-11-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_alter_historialestadoproyecto_id_alter_proyecto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='observaciones_aprobacion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
