# Generated by Django 3.1.2 on 2022-11-02 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo_proteccion_personal', '0001_initial'),
        ('nomencladores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipoproteccionpersonal',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomencladores.categoria'),
        ),
        migrations.AddField(
            model_name='equipoproteccionpersonal',
            name='entidad_importadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipoproteccionpersonal_entidad_importadora', to='nomencladores.entidad'),
        ),
        migrations.AddField(
            model_name='equipoproteccionpersonal',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipo_proteccion_personal.factura'),
        ),
        migrations.AddField(
            model_name='equipoproteccionpersonal',
            name='marca_comercial_registrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomencladores.marcacomercialregistrada'),
        ),
        migrations.AddField(
            model_name='equipoproteccionpersonal',
            name='numero_prefactura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo_proteccion_personal.numeroprefactura'),
        ),
        migrations.AddField(
            model_name='equipoproteccionpersonal',
            name='parte_cuerpo',
            field=models.ManyToManyField(related_name='parte_cuerpo', to='nomencladores.ParteCuerpo'),
        ),
        migrations.AddField(
            model_name='equipoproteccionpersonal',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
