# Generated by Django 4.1.3 on 2022-12-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='entidad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nombre',
        ),
    ]
