# Generated by Django 4.1.3 on 2022-12-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_user_apellidos_remove_user_entidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='municipio',
        ),
    ]
