# Generated by Django 4.1.3 on 2022-12-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_user_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='provincia',
        ),
        migrations.AddField(
            model_name='user',
            name='ciudad',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
