# Generated by Django 4.1.3 on 2022-11-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_proyecto_observaciones_aprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='precio_aprobacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
