# Generated by Django 4.1.3 on 2022-11-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [

        migrations.AlterField(
            model_name='actor',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='sexo',
            field=models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M'), ('Otro', 'Otro')], max_length=20),
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='facebook',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='precio_cup',
            new_name='precio_euro',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='precio_mlc',
        ),
        migrations.AddField(
            model_name='actor',
            name='observaciones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
